export const dataLiv = [
  {
    id: 1,
    destination: "Yaounde",
    source: "Bertoua",
    bus_matricule: "NTEST.B",
    bus_driver: "Stavro",
    date: "#30ad83",
    state: "En Chemin",
    action: "Validez l'arrivé",
  },
  {
    id: 2,
    destination: "Illaga-Papua Island",
    source: "Newport",
    bus_matricule: "MFO",
    bus_driver: "Izaak",
    date: "#29ee52",
    state: "En Chemin",
    action: "Validez l'arrivé",
  },
  {
    id: 3,
    destination: "Fort Leavenworth",
    source: "Terrace Bay, ON",
    bus_matricule: "RBC",
    bus_driver: "Domingo",
    date: "#98fd7e",
    state: "En Chemin",
    action: "Validez l'arrivé",
  },
  {
    id: 4,
    destination: "Mudanjiang",
    source: "Bouca",
    bus_matricule: "PFIS",
    bus_driver: "Jorgan",
    date: "#d59c8b",
    state: "Arrivé",
    action: "Validez l'arrivé",
  },
  {
    id: 5,
    destination: "Truth Or Consequences",
    source: "Salinas",
    bus_matricule: "NWFL",
    bus_driver: "Michail",
    date: "#69beba",
    state: "Arrivé",
    action: "Validez l'arrivé",
  },
  {
    id: 6,
    destination: "Bost",
    source: "Watertown",
    bus_matricule: "ABR^C",
    bus_driver: "Jamil",
    date: "#2be9bb",
    state: "En Chemin",
    action: "Validez l'arrivé",
  },
  {
    id: 7,
    destination: "Liepāja",
    source: "Cascade",
    bus_matricule: "PAY",
    bus_driver: "Torre",
    date: "#18454d",
    state: "En Chemin",
    action: "Validez l'arrivé",
  },
  {
    id: 8,
    destination: "Vredendal",
    source: "Baia Mare",
    bus_matricule: "COF^D",
    bus_driver: "Herby",
    date: "#ed9877",
    state: "Arrivée",
    action: "Validez l'arrivé",
  },
  {
    id: 9,
    destination: "Malelane",
    source: "Sahabat",
    bus_matricule: "KRA",
    bus_driver: "Berkly",
    date: "#2d4000",
    state: "Arrivé",
    action: "Validez l'arrivé",
  },
  {
    id: 10,
    destination: "Coron",
    source: "Verkhnevilyuisk",
    bus_matricule: "AJRD",
    bus_driver: "Lenci",
    date: "#64ab72",
    state: "En Chemin",
    action: "Validez l'arrivé",
  },
  {
    id: 11,
    destination: "Malelane",
    source: "Sahabat",
    bus_matricule: "KRA",
    bus_driver: "Berkly",
    date: "#2d4000",
    state: "Arrivé",
    action: "Validez l'arrivé",
  },
  {
    id: 12,
    destination: "Coron",
    source: "Verkhnevilyuisk",
    bus_matricule: "AJRD",
    bus_driver: "Lenci",
    date: "#64ab72",
    state: "En Chemin",
    action: "Validez l'arrivé",
  },
  {
    id: 13,
    destination: "Malelane",
    source: "Sahabat",
    bus_matricule: "KRA",
    bus_driver: "Berkly",
    date: "#2d4000",
    state: "Arrivé",
    action: "Validez l'arrivé",
  },
  {
    id: 14,
    destination: "Coron",
    source: "Verkhnevilyuisk",
    bus_matricule: "AJRD",
    bus_driver: "Lenci",
    date: "#64ab72",
    state: "En Chemin",
    action: "Validez l'arrivé",
  },
];
